[package]
name = "permit_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
syn = { version = "1.0", features = ["full", "derive", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0" 