version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - RUST_BACKTRACE=1
      - HTTP_PROXY=http://host.docker.internal:7893
      - HTTPS_PROXY=http://host.docker.internal:7893
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ../ruoyi-rust.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ruoyi-rust
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data: 